// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type {
	Command,
	CLI,
	GeneratedOptionMeta,
	RegisteredCommands,
	CommandOptions,
	GeneratedCommandMeta,
} from "@bunli/core"
import { createGeneratedHelpers, registerGeneratedStore } from "@bunli/core"

import Activate from "../src/cli/commands/activate.js"
import Build from "../src/cli/commands/build.js"
import Clean from "../src/cli/commands/clean.js"
import Init from "../src/cli/commands/init.js"
import List from "../src/cli/commands/list.js"
import New from "../src/cli/commands/new.js"
import Update from "../src/cli/commands/update.js"

// Narrow list of command names to avoid typeof-cycles in types
const names = ["activate", "build", "clean", "init", "list", "new", "update"] as const
type GeneratedNames = (typeof names)[number]

const modules: Record<GeneratedNames, Command<any>> = {
	activate: Activate,
	build: Build,
	clean: Clean,
	init: Init,
	list: List,
	new: New,
	update: Update,
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
	activate: {
		name: "activate",
		description: "Toggle extensions on/off and rebuild",
		options: {
			runtime: {
				type: "z.string.optional",
				required: false,
				hasDefault: false,
				description: 'Runtime for hooks: "bun" or "node" (auto-detected)',
				short: "r",
				schema: { type: "zod", method: "optional", args: [] },
				validator: "(val) => true",
			},
		},
		path: "./src/cli/commands/activate",
	},
	build: {
		name: "build",
		description: "Build all enabled extensions into .claude/hooks/",
		options: {
			runtime: {
				type: "z.string.optional",
				required: false,
				hasDefault: false,
				description: 'Runtime for hooks: "bun" or "node" (auto-detected)',
				short: "r",
				schema: { type: "zod", method: "optional", args: [] },
				validator: "(val) => true",
			},
		},
		path: "./src/cli/commands/build",
	},
	clean: {
		name: "clean",
		description: "Remove all hx artifacts from settings and hooks/",
		path: "./src/cli/commands/clean",
	},
	init: {
		name: "init",
		description: "Create .claude/extensions/ with a sample extension",
		path: "./src/cli/commands/init",
	},
	list: {
		name: "list",
		description: "List all extensions and their status",
		path: "./src/cli/commands/list",
	},
	new: {
		name: "new",
		description: "Scaffold a new extension",
		path: "./src/cli/commands/new",
	},
	update: {
		name: "update",
		description: "Update hx to the latest version",
		options: {
			latest: {
				type: "z.coerce.boolean.default",
				required: true,
				hasDefault: true,
				default: false,
				description: "Install from GitHub main branch (bleeding edge)",
				schema: {
					type: "zod",
					method: "default",
					args: [
						{
							type: "unknown",
							raw: {
								type: "BooleanLiteral",
								start: 230,
								end: 235,
								loc: {
									start: { line: 8, column: 44, index: 230 },
									end: { line: 8, column: 49, index: 235 },
								},
								value: false,
							},
						},
					],
				},
				validator: "(val) => true",
			},
		},
		path: "./src/cli/commands/update",
	},
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
	register(cli?: CLI<any>): GeneratedCLI
	list(): Array<{
		name: GeneratedNames
		command: (typeof modules)[GeneratedNames]
		metadata: (typeof metadata)[GeneratedNames]
	}>
	get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
	getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
	getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
	getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
	withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
	register: (cliInstance?: CLI<any>) => {
		generated.register(cliInstance)
		return cli
	},
	list: () => generated.list(),
	get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
	getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
	getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) =>
		generated.getFlags(name) as CommandOptions<Name>,
	getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
	withCLI: (cliInstance) => generated.withCLI(cliInstance),
}

// Enhanced helper functions
export const listCommands = () => generated.list().map((c) => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) =>
	generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) =>
	generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(
	name: Name,
	flags: Record<string, unknown>,
) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) =>
	generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) =>
	generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module "@bunli/core" {
	// Precise key mapping without typeof cycles
	interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
